# -*- coding: utf-8 -*-
"""PDS-08-23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvDDB9OaWgWTz2b8hmLSsHj9EMFnMdFT
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
car=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/car_price_dataset.csv')

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns


df= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/car_price_dataset.csv')
df = df.select_dtypes(include=np.number)


X = df.drop('Price', axis=1)
y = df['Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

knn_model = KNeighborsRegressor()
knn_model.fit(X_train_scaled, y_train)
knn_predictions = knn_model.predict(X_test_scaled)
knn_rmse = np.sqrt(mean_squared_error(y_test, knn_predictions))
print(f"KNN RMSE: {knn_rmse}")


linear_model = LinearRegression()
linear_model.fit(X_train_scaled, y_train)
linear_predictions = linear_model.predict(X_test_scaled)
linear_rmse = np.sqrt(mean_squared_error(y_test, linear_predictions))
print(f"Linear Regression RMSE: {linear_rmse}")


print("\nComparison:")
print(f"KNN RMSE: {knn_rmse}")
print(f"Linear Regression RMSE: {linear_rmse}")